[technote]
id = "DMTN-277"
series_id = "DMTN"
canonical_url = "https://dmtn-277.lsst.io/"
github_url = "https://github.com/lsst-dm/dmtn-277"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
extensions = ["myst_parser"]

[technote.status]
state = "draft"

[[technote.authors]]
name = {given = "Peter S.", family = "Ferguson"}
internal_id = "fergusonps"
orcid = "https://orcid.org/0000-0001-6957-1627"
[[technote.authors.affiliations]]
name = "Department of Physics"
internal_id = "WisconsinMadison"
address = "University of Wisconsin-Madison, Madison, WI 53706, USA"

[[technote.authors]]
name = {given = "Eli S.", family = "Rykoff"}
internal_id = "rykoffe"
orcid = "https://orcid.org/0000-0001-9376-3135"
[[technote.authors.affiliations]]
name = "Kavli Institute for Particle Astrophysics and Cosmology"
internal_id = "SLAC-Kavli"
address = "SLAC National Accelerator Laboratory, Stanford University, Stanford, CA 94025, USA"

[[technote.authors]]
name = {given = "Jeffrey L.", family = "Carlin"}
internal_id = "carlinjl"
orcid = "https://orcid.org/0000-0002-3936-9628"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"

[[technote.authors]]
name = {given = "Clare", family = "Saunders"}
internal_id = "saundersc"
orcid = "https://orcid.org/0000-0002-3936-9628"
[[technote.authors.affiliations]]
name = "Princeton University"
internal_id = "Princeton-Astro"
address = "Department of Astrophysical Sciences, Princeton University, Princeton, NJ 08544, USA"

[[technote.authors]]
name = {given = "John K.", family = "Parejko"}
internal_id = "parejkojk"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"
